version: '3'

services:
  mysql:
    container_name: tournaments_mysql
    image: percona/percona-server:latest
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tournaments
      MYSQL_USER: tournaments
      MYSQL_PASSWORD: tournaments
    networks:
      - network
    healthcheck:
      test: mysql -u tournaments -ptournaments -D tournaments -e "SELECT 1;"
      interval: 5s
      timeout: 5s
      retries: 30
  php:
    container_name: tournaments_php
    build: ./docker/php
    volumes:
      - ./:/var/www/tournaments
    environment:
      PHP_IDE_CONFIG: serverName=tournaments.local
#      XDEBUG_CONFIG: client_host=192.168.99.1
      XDEBUG_ENABLE: ${XDEBUG_ENABLE:-debug}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network
  nginx:
    container_name: tournaments_nginx
    build: ./docker/nginx
    ports:
      - "88:80"
    volumes:
      - ./docker/nginx/tournaments.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - network

networks:
  network:
    driver: bridge
